### ISSUE TITLE
integration with xgcm discussion

### ISSUE THREAD

**Issue by rabernat** [ECCO-GROUP/ECCO-v4-Python-Tutorial#1]
I just went through these tutorials. They are really beautiful! Fantastic work @ifenty! This is a fantastic service to the community you have done here.

As we discussed at OSM, there are a couple of points where xgcm could help with some of the pain points regarding differencing / interpolating to / from cell faces / centers. Once xgcm/xgcm#88 is merged, it will also be able to help a lot with tile-related stuff.

But I think there are still many questions to resolve, such as
- what is the appropriate level of complexity to expose to the general user (xgcm is still pretty low-level)?
- what features belong in xgcm vs. ECCOv4-py vs. the tutorial notebooks?

I wanted to open this issue just to keep the discussion going, without suggesting a specific course of action yet.

**Comment by ifenty** [comment]
@rabernat as many features in xgcm as possible. My vision is  for ECCOv4-py (and whatever comes after) to be a place where folks can learn how to do the calculations they need to do (and maybe come away with some new ideas for calculations) and for it to showcase tools that enable those calculations -- xgcm being of course the most important of those.

I need to get a refresh on what new capabilities are in xgcm and if other tools that would be useful for the MITgcm/ECCO community are out there!
