### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by rcaneill** [ECCO-GROUP/ECCO-v4-Python-Tutorial#14]
Hello,

The last link of the `doc/Downloading_the_ECCO_v4_state_estimate.rst` (https://ecco.jpl.nasa.gov/products/latest/) is broken and leads to a 404 Error.

Best

**Comment by ifenty** [comment]
Hi Romain,
Thanks!  I fixed it to redirect to: https://ecco-group.org

I'd be happy to help you find the right state estimate for your research.  The latest solution is V4r4.  We recently uploaded the latest and greatest to NASA's PO.DAAC.  The same solution (with less good metadata is up on our  ecco-drive).


Ian Fenty
Ian.Fenty@jpl.nasa.gov
