### ISSUE TITLE
Broken link: instructions to re-run ECCO for custom output

### ISSUE THREAD

**Issue by ali-ramadhan** [ECCO-GROUP/ECCO-v4-Python-Tutorial#15]
https://github.com/ECCO-GROUP/ECCO-v4-Python-Tutorial/blob/bcdcca2ccd2cfe07d12ca85d4df9c93ac85490c2/doc/fields.rst#L67

I get a 404 not found error when visiting https://ecco.jpl.nasa.gov/drive/files/Version4/Release3/doc/ECCOv4r3_reproduction.pdf

**Comment by ifenty** [comment]
Hi Ali,
I fixed the link.  It should point to: https://ecco.jpl.nasa.gov/drive/files/Version4/Release3/doc/v4r3_reproduction_howto.pdf

May I ask what your interest is in the V4r3 solution?  There is a newer solution, V4r4,  also available.

Ian
Ian.Fenty@jpl.nasa.gov

**Comment by ali-ramadhan** [comment]
Thanks for the quick fix @ifenty!

Ah I didn't realize the link was particular to V4r3. I'm currently browsing/downloading the V4r4 solution through ECCO's WebDAV interface.

Was just curious what running ECCO involved in case I needed to run it for custom output. But the daily tiled output on the ECCO Drive should work great for our use case since we mostly just need vertical profiles.

I'm hoping to use ECCO data to initialize and force LES simulations of boundary layer turbulence, e.g. https://github.com/CliMA/LESbrary.jl/pull/93

**Comment by ifenty** [comment]
Ali,

Very cool.  We just uploaded an 'updated' ECCO V4r4 files to NASA's PO.DAAC (which will now be the long term ecco archive).  These files should have the same fields as what's on the WebDAV but they will have the latest and greatest (and much improved) metadata.  Take a look here: 
https://search.earthdata.nasa.gov/search?q=ecco&m=-0.0703125!0.0703125!2!1!0!0%2C2

We'll be taking the WebDAV offline soon.   If you did download from PO.DAAC you'd be FIRST!

-Ian

**Comment by ali-ramadhan** [comment]
Thanks for the heads up! Global attributes now fill my screen 🚀 

![image](https://user-images.githubusercontent.com/20099589/109060250-2e1fed80-76b3-11eb-8d38-a6307d97eb4c.png)
