### ISSUE TITLE
TypeError: load_ecco_grid_nc() missing 1 required positional argument: 'grid_filename'

### ISSUE THREAD

**Issue by JenniferSW** [ECCO-GROUP/ECCO-v4-Python-Tutorial#21]
Hey, 
I just tried to read in the Ecco grid using this part of your tutorial but I get an error message saying 'TypeError: load_ecco_grid_nc() missing 1 required positional argument: 'grid_filename''.
In the documentation, they are always referencing a single netCDF file for the Ecco grid. 
Do you know if it is possible to read in the 13 single netCDF files for the Ecco grid?
Thanks in advance!

https://github.com/ECCO-GROUP/ECCO-v4-Python-Tutorial/blob/32ec12ab85ee51f81b8044c0c98743baca92767c/Tutorials_as_Python_Files/ECCO_v4_Example_MHT.py#L84

**Comment by ifenty** [comment]
@JenniferSW thanks for pointing out this bug.  In fact, we moved away from having 13 single netCDF files in favor of a single netCDF that contains info for all 13 tiles.  You don't need a special routine to read it.  In Python you can read the single file as:
```
ecco_grid = xr.open_dataset('ECCO-GRID.nc')
```

If you downloaded the ECCO V4r4 files from the ECCO Drive webdav, that single *ECCO-GRID.nc* file is here: 
```
files / Version4 / Release4 / nctiles_grid / ECCO-GRID.nc
```

In the last month or so we started hosting ECCO fields on NASA's PODAAC,
https://podaac.jpl.nasa.gov/ECCO

But it will take a little while for us to update the tutorial.
